<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>WELCOME</title>
</head>
<body>
<h2>Registration</h2>
<form action="/tryregistration" method="post">
    <label for="login">Login:</label><br>
    <input type="text" id="login" name="login"><br>
    <label for="password">Password:</label><br>
    <input type="text" id="password" name="password"><br><br>
    <label for="repeat_password">Repeat Password:</label><br>
    <input type="text" id="repeat_password" name="repeat_password"><br><br>
    <label for="email">Email:</label><br>
    <input type="text" id="email" name="email"><br><br>
    <label for="phone">Phone Number:</label><br>
    <input type="text" id="phone" name="phone" ><br><br>
    <input type="submit" value="Registration">
</form>
</body>
</html>
